#!/usr/bin/env bash
set -e

if `command -v deactivate`; then
    deactivate
fi

# create virtual environment
rm -rf .venv ./*.egg-info dist
python3 -m venv .venv
source .venv/bin/activate

# upgrade pip and install requirements
python3 -m pip install --upgrade pip setuptools wheel
if [ -f "requirements.txt" ]; then
    python3 -m pip install -r requirements.txt
fi

# install pre-commit hooks
pre-commit install
