#!/usr/bin/env bash
set -e

if ! [ -d ".venv" ]; then
    python3 -m venv .venv
fi

source .venv/bin/activate

# install dev dependencies
python3 -m pip install -r requirements-dev.txt

# install pre-commit hooks
pre-commit install

# install generate script
cd .bin
npm ci
cd ..
